/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var enum_pb = require('./enum_pb.js');
var filter_pb = require('./filter_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.exportSymbol('proto.statistico.StrategyTrade', null, global);
goog.exportSymbol('proto.statistico.StrategyTradeSearchRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.StrategyTradeSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.statistico.StrategyTradeSearchRequest.repeatedFields_, null);
};
goog.inherits(proto.statistico.StrategyTradeSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.StrategyTradeSearchRequest.displayName = 'proto.statistico.StrategyTradeSearchRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.statistico.StrategyTradeSearchRequest.repeatedFields_ = [7,8,11,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.StrategyTradeSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.StrategyTradeSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTradeSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    market: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runner: jspb.Message.getFieldWithDefault(msg, 2, ""),
    minOdds: (f = msg.getMinOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    maxOdds: (f = msg.getMaxOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    line: jspb.Message.getFieldWithDefault(msg, 5, ""),
    side: jspb.Message.getFieldWithDefault(msg, 6, 0),
    competitionIdsList: jspb.Message.getRepeatedField(msg, 7),
    seasonIdsList: jspb.Message.getRepeatedField(msg, 8),
    datefrom: (f = msg.getDatefrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    dateto: (f = msg.getDateto()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    resultFiltersList: jspb.Message.toObjectList(msg.getResultFiltersList(),
    filter_pb.ResultFilter.toObject, includeInstance),
    statFiltersList: jspb.Message.toObjectList(msg.getStatFiltersList(),
    filter_pb.StatFilter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.StrategyTradeSearchRequest}
 */
proto.statistico.StrategyTradeSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.StrategyTradeSearchRequest;
  return proto.statistico.StrategyTradeSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.StrategyTradeSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.StrategyTradeSearchRequest}
 */
proto.statistico.StrategyTradeSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunner(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMinOdds(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMaxOdds(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine(value);
      break;
    case 6:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setCompetitionIdsList(value);
      break;
    case 8:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setSeasonIdsList(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDatefrom(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateto(value);
      break;
    case 11:
      var value = new filter_pb.ResultFilter;
      reader.readMessage(value,filter_pb.ResultFilter.deserializeBinaryFromReader);
      msg.addResultFilters(value);
      break;
    case 12:
      var value = new filter_pb.StatFilter;
      reader.readMessage(value,filter_pb.StatFilter.deserializeBinaryFromReader);
      msg.addStatFilters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.StrategyTradeSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.StrategyTradeSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTradeSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunner();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMinOdds();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getMaxOdds();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getLine();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getCompetitionIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      7,
      f
    );
  }
  f = message.getSeasonIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      8,
      f
    );
  }
  f = message.getDatefrom();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDateto();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResultFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      filter_pb.ResultFilter.serializeBinaryToWriter
    );
  }
  f = message.getStatFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      filter_pb.StatFilter.serializeBinaryToWriter
    );
  }
};


/**
 * optional string market = 1;
 * @return {string}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setMarket = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string runner = 2;
 * @return {string}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getRunner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setRunner = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.FloatValue min_odds = 3;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getMinOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 3));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setMinOdds = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearMinOdds = function() {
  this.setMinOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.hasMinOdds = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.FloatValue max_odds = 4;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getMaxOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 4));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setMaxOdds = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearMaxOdds = function() {
  this.setMaxOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.hasMaxOdds = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string line = 5;
 * @return {string}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getLine = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setLine = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional SideEnum side = 6;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.statistico.SideEnum} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setSide = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * repeated uint64 competition_ids = 7;
 * @return {!Array<number>}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getCompetitionIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<number>} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setCompetitionIdsList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.statistico.StrategyTradeSearchRequest.prototype.addCompetitionIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearCompetitionIdsList = function() {
  this.setCompetitionIdsList([]);
};


/**
 * repeated uint64 season_ids = 8;
 * @return {!Array<number>}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getSeasonIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<number>} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setSeasonIdsList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.statistico.StrategyTradeSearchRequest.prototype.addSeasonIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearSeasonIdsList = function() {
  this.setSeasonIdsList([]);
};


/**
 * optional google.protobuf.Timestamp dateFrom = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getDatefrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setDatefrom = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearDatefrom = function() {
  this.setDatefrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.hasDatefrom = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp dateTo = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getDateto = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setDateto = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearDateto = function() {
  this.setDateto(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.hasDateto = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated ResultFilter result_filters = 11;
 * @return {!Array<!proto.statistico.ResultFilter>}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getResultFiltersList = function() {
  return /** @type{!Array<!proto.statistico.ResultFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.ResultFilter, 11));
};


/** @param {!Array<!proto.statistico.ResultFilter>} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setResultFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.statistico.ResultFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.ResultFilter}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.addResultFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.statistico.ResultFilter, opt_index);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearResultFiltersList = function() {
  this.setResultFiltersList([]);
};


/**
 * repeated StatFilter stat_filters = 12;
 * @return {!Array<!proto.statistico.StatFilter>}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.getStatFiltersList = function() {
  return /** @type{!Array<!proto.statistico.StatFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.StatFilter, 12));
};


/** @param {!Array<!proto.statistico.StatFilter>} value */
proto.statistico.StrategyTradeSearchRequest.prototype.setStatFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.statistico.StatFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.StatFilter}
 */
proto.statistico.StrategyTradeSearchRequest.prototype.addStatFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.statistico.StatFilter, opt_index);
};


proto.statistico.StrategyTradeSearchRequest.prototype.clearStatFiltersList = function() {
  this.setStatFiltersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.StrategyTrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.statistico.StrategyTrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.StrategyTrade.displayName = 'proto.statistico.StrategyTrade';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.StrategyTrade.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.StrategyTrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.StrategyTrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTrade.toObject = function(includeInstance, msg) {
  var f, obj = {
    marketName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runnerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    runnerPrice: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    side: jspb.Message.getFieldWithDefault(msg, 4, 0),
    eventId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    competitionId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    seasonId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    eventDate: (f = msg.getEventDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    result: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.StrategyTrade}
 */
proto.statistico.StrategyTrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.StrategyTrade;
  return proto.statistico.StrategyTrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.StrategyTrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.StrategyTrade}
 */
proto.statistico.StrategyTrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunnerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRunnerPrice(value);
      break;
    case 4:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEventId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCompetitionId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSeasonId(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEventDate(value);
      break;
    case 9:
      var value = /** @type {!proto.statistico.TradeResultEnum} */ (reader.readEnum());
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.StrategyTrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.StrategyTrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.StrategyTrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarketName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunnerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRunnerPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getEventId();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getCompetitionId();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getSeasonId();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getEventDate();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional string market_name = 1;
 * @return {string}
 */
proto.statistico.StrategyTrade.prototype.getMarketName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.StrategyTrade.prototype.setMarketName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string runner_name = 2;
 * @return {string}
 */
proto.statistico.StrategyTrade.prototype.getRunnerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.statistico.StrategyTrade.prototype.setRunnerName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float runner_price = 3;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getRunnerPrice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setRunnerPrice = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional SideEnum side = 4;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.StrategyTrade.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.statistico.SideEnum} value */
proto.statistico.StrategyTrade.prototype.setSide = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional uint64 event_id = 5;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setEventId = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 competition_id = 6;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getCompetitionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setCompetitionId = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 season_id = 7;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getSeasonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setSeasonId = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional google.protobuf.Timestamp event_date = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.StrategyTrade.prototype.getEventDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.StrategyTrade.prototype.setEventDate = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.statistico.StrategyTrade.prototype.clearEventDate = function() {
  this.setEventDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.StrategyTrade.prototype.hasEventDate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional TradeResultEnum result = 9;
 * @return {!proto.statistico.TradeResultEnum}
 */
proto.statistico.StrategyTrade.prototype.getResult = function() {
  return /** @type {!proto.statistico.TradeResultEnum} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.statistico.TradeResultEnum} value */
proto.statistico.StrategyTrade.prototype.setResult = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};


goog.object.extend(exports, proto.statistico);
