/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var enum_pb = require('./enum_pb.js');
var filter_pb = require('./filter_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.exportSymbol('proto.statistico.BuildStrategyRequest', null, global);
goog.exportSymbol('proto.statistico.ListUserStrategiesRequest', null, global);
goog.exportSymbol('proto.statistico.SaveStrategyRequest', null, global);
goog.exportSymbol('proto.statistico.StakingPlan', null, global);
goog.exportSymbol('proto.statistico.Strategy', null, global);
goog.exportSymbol('proto.statistico.StrategyTrade', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.BuildStrategyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.statistico.BuildStrategyRequest.repeatedFields_, null);
};
goog.inherits(proto.statistico.BuildStrategyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.BuildStrategyRequest.displayName = 'proto.statistico.BuildStrategyRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.statistico.BuildStrategyRequest.repeatedFields_ = [7,8,11,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.BuildStrategyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.BuildStrategyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.BuildStrategyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.BuildStrategyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    market: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runner: jspb.Message.getFieldWithDefault(msg, 2, ""),
    minOdds: (f = msg.getMinOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    maxOdds: (f = msg.getMaxOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    line: jspb.Message.getFieldWithDefault(msg, 5, ""),
    side: jspb.Message.getFieldWithDefault(msg, 6, 0),
    competitionIdsList: jspb.Message.getRepeatedField(msg, 7),
    seasonIdsList: jspb.Message.getRepeatedField(msg, 8),
    datefrom: (f = msg.getDatefrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    dateto: (f = msg.getDateto()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    resultFiltersList: jspb.Message.toObjectList(msg.getResultFiltersList(),
    filter_pb.ResultFilter.toObject, includeInstance),
    statFiltersList: jspb.Message.toObjectList(msg.getStatFiltersList(),
    filter_pb.StatFilter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.BuildStrategyRequest}
 */
proto.statistico.BuildStrategyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.BuildStrategyRequest;
  return proto.statistico.BuildStrategyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.BuildStrategyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.BuildStrategyRequest}
 */
proto.statistico.BuildStrategyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunner(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMinOdds(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMaxOdds(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLine(value);
      break;
    case 6:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setCompetitionIdsList(value);
      break;
    case 8:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setSeasonIdsList(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDatefrom(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateto(value);
      break;
    case 11:
      var value = new filter_pb.ResultFilter;
      reader.readMessage(value,filter_pb.ResultFilter.deserializeBinaryFromReader);
      msg.addResultFilters(value);
      break;
    case 12:
      var value = new filter_pb.StatFilter;
      reader.readMessage(value,filter_pb.StatFilter.deserializeBinaryFromReader);
      msg.addStatFilters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.BuildStrategyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.BuildStrategyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.BuildStrategyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.BuildStrategyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunner();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMinOdds();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getMaxOdds();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getLine();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getCompetitionIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      7,
      f
    );
  }
  f = message.getSeasonIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      8,
      f
    );
  }
  f = message.getDatefrom();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDateto();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResultFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      filter_pb.ResultFilter.serializeBinaryToWriter
    );
  }
  f = message.getStatFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      filter_pb.StatFilter.serializeBinaryToWriter
    );
  }
};


/**
 * optional string market = 1;
 * @return {string}
 */
proto.statistico.BuildStrategyRequest.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.BuildStrategyRequest.prototype.setMarket = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string runner = 2;
 * @return {string}
 */
proto.statistico.BuildStrategyRequest.prototype.getRunner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.statistico.BuildStrategyRequest.prototype.setRunner = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.FloatValue min_odds = 3;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.BuildStrategyRequest.prototype.getMinOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 3));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.BuildStrategyRequest.prototype.setMinOdds = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.statistico.BuildStrategyRequest.prototype.clearMinOdds = function() {
  this.setMinOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.BuildStrategyRequest.prototype.hasMinOdds = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.FloatValue max_odds = 4;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.BuildStrategyRequest.prototype.getMaxOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 4));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.BuildStrategyRequest.prototype.setMaxOdds = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.statistico.BuildStrategyRequest.prototype.clearMaxOdds = function() {
  this.setMaxOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.BuildStrategyRequest.prototype.hasMaxOdds = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string line = 5;
 * @return {string}
 */
proto.statistico.BuildStrategyRequest.prototype.getLine = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.statistico.BuildStrategyRequest.prototype.setLine = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional SideEnum side = 6;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.BuildStrategyRequest.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.statistico.SideEnum} value */
proto.statistico.BuildStrategyRequest.prototype.setSide = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * repeated uint64 competition_ids = 7;
 * @return {!Array<number>}
 */
proto.statistico.BuildStrategyRequest.prototype.getCompetitionIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<number>} value */
proto.statistico.BuildStrategyRequest.prototype.setCompetitionIdsList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.statistico.BuildStrategyRequest.prototype.addCompetitionIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.statistico.BuildStrategyRequest.prototype.clearCompetitionIdsList = function() {
  this.setCompetitionIdsList([]);
};


/**
 * repeated uint64 season_ids = 8;
 * @return {!Array<number>}
 */
proto.statistico.BuildStrategyRequest.prototype.getSeasonIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<number>} value */
proto.statistico.BuildStrategyRequest.prototype.setSeasonIdsList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.statistico.BuildStrategyRequest.prototype.addSeasonIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.statistico.BuildStrategyRequest.prototype.clearSeasonIdsList = function() {
  this.setSeasonIdsList([]);
};


/**
 * optional google.protobuf.Timestamp dateFrom = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.BuildStrategyRequest.prototype.getDatefrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.BuildStrategyRequest.prototype.setDatefrom = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.statistico.BuildStrategyRequest.prototype.clearDatefrom = function() {
  this.setDatefrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.BuildStrategyRequest.prototype.hasDatefrom = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp dateTo = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.BuildStrategyRequest.prototype.getDateto = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.BuildStrategyRequest.prototype.setDateto = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.statistico.BuildStrategyRequest.prototype.clearDateto = function() {
  this.setDateto(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.BuildStrategyRequest.prototype.hasDateto = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated ResultFilter result_filters = 11;
 * @return {!Array<!proto.statistico.ResultFilter>}
 */
proto.statistico.BuildStrategyRequest.prototype.getResultFiltersList = function() {
  return /** @type{!Array<!proto.statistico.ResultFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.ResultFilter, 11));
};


/** @param {!Array<!proto.statistico.ResultFilter>} value */
proto.statistico.BuildStrategyRequest.prototype.setResultFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.statistico.ResultFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.ResultFilter}
 */
proto.statistico.BuildStrategyRequest.prototype.addResultFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.statistico.ResultFilter, opt_index);
};


proto.statistico.BuildStrategyRequest.prototype.clearResultFiltersList = function() {
  this.setResultFiltersList([]);
};


/**
 * repeated StatFilter stat_filters = 12;
 * @return {!Array<!proto.statistico.StatFilter>}
 */
proto.statistico.BuildStrategyRequest.prototype.getStatFiltersList = function() {
  return /** @type{!Array<!proto.statistico.StatFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.StatFilter, 12));
};


/** @param {!Array<!proto.statistico.StatFilter>} value */
proto.statistico.BuildStrategyRequest.prototype.setStatFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.statistico.StatFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.StatFilter}
 */
proto.statistico.BuildStrategyRequest.prototype.addStatFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.statistico.StatFilter, opt_index);
};


proto.statistico.BuildStrategyRequest.prototype.clearStatFiltersList = function() {
  this.setStatFiltersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.ListUserStrategiesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.statistico.ListUserStrategiesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.ListUserStrategiesRequest.displayName = 'proto.statistico.ListUserStrategiesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.ListUserStrategiesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.ListUserStrategiesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.ListUserStrategiesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.ListUserStrategiesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.ListUserStrategiesRequest}
 */
proto.statistico.ListUserStrategiesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.ListUserStrategiesRequest;
  return proto.statistico.ListUserStrategiesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.ListUserStrategiesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.ListUserStrategiesRequest}
 */
proto.statistico.ListUserStrategiesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.ListUserStrategiesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.ListUserStrategiesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.ListUserStrategiesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.ListUserStrategiesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.statistico.ListUserStrategiesRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.ListUserStrategiesRequest.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.SaveStrategyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.statistico.SaveStrategyRequest.repeatedFields_, null);
};
goog.inherits(proto.statistico.SaveStrategyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.SaveStrategyRequest.displayName = 'proto.statistico.SaveStrategyRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.statistico.SaveStrategyRequest.repeatedFields_ = [8,9,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.SaveStrategyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.SaveStrategyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.SaveStrategyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.SaveStrategyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    market: jspb.Message.getFieldWithDefault(msg, 3, ""),
    runner: jspb.Message.getFieldWithDefault(msg, 4, ""),
    minOdds: (f = msg.getMinOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    maxOdds: (f = msg.getMaxOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    side: jspb.Message.getFieldWithDefault(msg, 7, 0),
    competitionIdsList: jspb.Message.getRepeatedField(msg, 8),
    resultFiltersList: jspb.Message.toObjectList(msg.getResultFiltersList(),
    filter_pb.ResultFilter.toObject, includeInstance),
    statFiltersList: jspb.Message.toObjectList(msg.getStatFiltersList(),
    filter_pb.StatFilter.toObject, includeInstance),
    visibility: jspb.Message.getFieldWithDefault(msg, 11, 0),
    stakingPlan: (f = msg.getStakingPlan()) && proto.statistico.StakingPlan.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.SaveStrategyRequest}
 */
proto.statistico.SaveStrategyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.SaveStrategyRequest;
  return proto.statistico.SaveStrategyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.SaveStrategyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.SaveStrategyRequest}
 */
proto.statistico.SaveStrategyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunner(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMinOdds(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMaxOdds(value);
      break;
    case 7:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 8:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setCompetitionIdsList(value);
      break;
    case 9:
      var value = new filter_pb.ResultFilter;
      reader.readMessage(value,filter_pb.ResultFilter.deserializeBinaryFromReader);
      msg.addResultFilters(value);
      break;
    case 10:
      var value = new filter_pb.StatFilter;
      reader.readMessage(value,filter_pb.StatFilter.deserializeBinaryFromReader);
      msg.addStatFilters(value);
      break;
    case 11:
      var value = /** @type {!proto.statistico.VisibilityEnum} */ (reader.readEnum());
      msg.setVisibility(value);
      break;
    case 14:
      var value = new proto.statistico.StakingPlan;
      reader.readMessage(value,proto.statistico.StakingPlan.deserializeBinaryFromReader);
      msg.setStakingPlan(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.SaveStrategyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.SaveStrategyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.SaveStrategyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.SaveStrategyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRunner();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMinOdds();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getMaxOdds();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getCompetitionIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      8,
      f
    );
  }
  f = message.getResultFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      filter_pb.ResultFilter.serializeBinaryToWriter
    );
  }
  f = message.getStatFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      filter_pb.StatFilter.serializeBinaryToWriter
    );
  }
  f = message.getVisibility();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getStakingPlan();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.statistico.StakingPlan.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.statistico.SaveStrategyRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.SaveStrategyRequest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.statistico.SaveStrategyRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.statistico.SaveStrategyRequest.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string market = 3;
 * @return {string}
 */
proto.statistico.SaveStrategyRequest.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.statistico.SaveStrategyRequest.prototype.setMarket = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string runner = 4;
 * @return {string}
 */
proto.statistico.SaveStrategyRequest.prototype.getRunner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.statistico.SaveStrategyRequest.prototype.setRunner = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.FloatValue min_odds = 5;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.SaveStrategyRequest.prototype.getMinOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 5));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.SaveStrategyRequest.prototype.setMinOdds = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.statistico.SaveStrategyRequest.prototype.clearMinOdds = function() {
  this.setMinOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.SaveStrategyRequest.prototype.hasMinOdds = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.FloatValue max_odds = 6;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.SaveStrategyRequest.prototype.getMaxOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 6));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.SaveStrategyRequest.prototype.setMaxOdds = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.statistico.SaveStrategyRequest.prototype.clearMaxOdds = function() {
  this.setMaxOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.SaveStrategyRequest.prototype.hasMaxOdds = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SideEnum side = 7;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.SaveStrategyRequest.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.statistico.SideEnum} value */
proto.statistico.SaveStrategyRequest.prototype.setSide = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * repeated uint64 competition_ids = 8;
 * @return {!Array<number>}
 */
proto.statistico.SaveStrategyRequest.prototype.getCompetitionIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<number>} value */
proto.statistico.SaveStrategyRequest.prototype.setCompetitionIdsList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.statistico.SaveStrategyRequest.prototype.addCompetitionIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.statistico.SaveStrategyRequest.prototype.clearCompetitionIdsList = function() {
  this.setCompetitionIdsList([]);
};


/**
 * repeated ResultFilter result_filters = 9;
 * @return {!Array<!proto.statistico.ResultFilter>}
 */
proto.statistico.SaveStrategyRequest.prototype.getResultFiltersList = function() {
  return /** @type{!Array<!proto.statistico.ResultFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.ResultFilter, 9));
};


/** @param {!Array<!proto.statistico.ResultFilter>} value */
proto.statistico.SaveStrategyRequest.prototype.setResultFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.statistico.ResultFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.ResultFilter}
 */
proto.statistico.SaveStrategyRequest.prototype.addResultFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.statistico.ResultFilter, opt_index);
};


proto.statistico.SaveStrategyRequest.prototype.clearResultFiltersList = function() {
  this.setResultFiltersList([]);
};


/**
 * repeated StatFilter stat_filters = 10;
 * @return {!Array<!proto.statistico.StatFilter>}
 */
proto.statistico.SaveStrategyRequest.prototype.getStatFiltersList = function() {
  return /** @type{!Array<!proto.statistico.StatFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.StatFilter, 10));
};


/** @param {!Array<!proto.statistico.StatFilter>} value */
proto.statistico.SaveStrategyRequest.prototype.setStatFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.statistico.StatFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.StatFilter}
 */
proto.statistico.SaveStrategyRequest.prototype.addStatFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.statistico.StatFilter, opt_index);
};


proto.statistico.SaveStrategyRequest.prototype.clearStatFiltersList = function() {
  this.setStatFiltersList([]);
};


/**
 * optional VisibilityEnum visibility = 11;
 * @return {!proto.statistico.VisibilityEnum}
 */
proto.statistico.SaveStrategyRequest.prototype.getVisibility = function() {
  return /** @type {!proto.statistico.VisibilityEnum} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {!proto.statistico.VisibilityEnum} value */
proto.statistico.SaveStrategyRequest.prototype.setVisibility = function(value) {
  jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional StakingPlan staking_plan = 14;
 * @return {?proto.statistico.StakingPlan}
 */
proto.statistico.SaveStrategyRequest.prototype.getStakingPlan = function() {
  return /** @type{?proto.statistico.StakingPlan} */ (
    jspb.Message.getWrapperField(this, proto.statistico.StakingPlan, 14));
};


/** @param {?proto.statistico.StakingPlan|undefined} value */
proto.statistico.SaveStrategyRequest.prototype.setStakingPlan = function(value) {
  jspb.Message.setWrapperField(this, 14, value);
};


proto.statistico.SaveStrategyRequest.prototype.clearStakingPlan = function() {
  this.setStakingPlan(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.SaveStrategyRequest.prototype.hasStakingPlan = function() {
  return jspb.Message.getField(this, 14) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.Strategy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.statistico.Strategy.repeatedFields_, null);
};
goog.inherits(proto.statistico.Strategy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.Strategy.displayName = 'proto.statistico.Strategy';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.statistico.Strategy.repeatedFields_ = [9,14,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.Strategy.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.Strategy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.Strategy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.Strategy.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    market: jspb.Message.getFieldWithDefault(msg, 5, ""),
    runner: jspb.Message.getFieldWithDefault(msg, 6, ""),
    minOdds: (f = msg.getMinOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    maxOdds: (f = msg.getMaxOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    competitionIdsList: jspb.Message.getRepeatedField(msg, 9),
    side: jspb.Message.getFieldWithDefault(msg, 10, 0),
    visibility: jspb.Message.getFieldWithDefault(msg, 11, 0),
    status: jspb.Message.getFieldWithDefault(msg, 12, 0),
    stakingPlan: (f = msg.getStakingPlan()) && proto.statistico.StakingPlan.toObject(includeInstance, f),
    resultFiltersList: jspb.Message.toObjectList(msg.getResultFiltersList(),
    filter_pb.ResultFilter.toObject, includeInstance),
    statFiltersList: jspb.Message.toObjectList(msg.getStatFiltersList(),
    filter_pb.StatFilter.toObject, includeInstance),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.Strategy}
 */
proto.statistico.Strategy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.Strategy;
  return proto.statistico.Strategy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.Strategy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.Strategy}
 */
proto.statistico.Strategy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunner(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMinOdds(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMaxOdds(value);
      break;
    case 9:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setCompetitionIdsList(value);
      break;
    case 10:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 11:
      var value = /** @type {!proto.statistico.VisibilityEnum} */ (reader.readEnum());
      msg.setVisibility(value);
      break;
    case 12:
      var value = /** @type {!proto.statistico.StrategyStatusEnum} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 13:
      var value = new proto.statistico.StakingPlan;
      reader.readMessage(value,proto.statistico.StakingPlan.deserializeBinaryFromReader);
      msg.setStakingPlan(value);
      break;
    case 14:
      var value = new filter_pb.ResultFilter;
      reader.readMessage(value,filter_pb.ResultFilter.deserializeBinaryFromReader);
      msg.addResultFilters(value);
      break;
    case 15:
      var value = new filter_pb.StatFilter;
      reader.readMessage(value,filter_pb.StatFilter.deserializeBinaryFromReader);
      msg.addStatFilters(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 17:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.Strategy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.Strategy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.Strategy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.Strategy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRunner();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMinOdds();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getMaxOdds();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getCompetitionIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      9,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getVisibility();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getStakingPlan();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.statistico.StakingPlan.serializeBinaryToWriter
    );
  }
  f = message.getResultFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      filter_pb.ResultFilter.serializeBinaryToWriter
    );
  }
  f = message.getStatFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      filter_pb.StatFilter.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.Strategy.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.statistico.Strategy.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.statistico.Strategy.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string user_id = 4;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.statistico.Strategy.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string market = 5;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.statistico.Strategy.prototype.setMarket = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string runner = 6;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getRunner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.statistico.Strategy.prototype.setRunner = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional google.protobuf.FloatValue min_odds = 7;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.Strategy.prototype.getMinOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 7));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.Strategy.prototype.setMinOdds = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.statistico.Strategy.prototype.clearMinOdds = function() {
  this.setMinOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.Strategy.prototype.hasMinOdds = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.FloatValue max_odds = 8;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.Strategy.prototype.getMaxOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 8));
};


/** @param {?proto.google.protobuf.FloatValue|undefined} value */
proto.statistico.Strategy.prototype.setMaxOdds = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.statistico.Strategy.prototype.clearMaxOdds = function() {
  this.setMaxOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.Strategy.prototype.hasMaxOdds = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated uint64 competition_ids = 9;
 * @return {!Array<number>}
 */
proto.statistico.Strategy.prototype.getCompetitionIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<number>} value */
proto.statistico.Strategy.prototype.setCompetitionIdsList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.statistico.Strategy.prototype.addCompetitionIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


proto.statistico.Strategy.prototype.clearCompetitionIdsList = function() {
  this.setCompetitionIdsList([]);
};


/**
 * optional SideEnum side = 10;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.Strategy.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {!proto.statistico.SideEnum} value */
proto.statistico.Strategy.prototype.setSide = function(value) {
  jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * optional VisibilityEnum visibility = 11;
 * @return {!proto.statistico.VisibilityEnum}
 */
proto.statistico.Strategy.prototype.getVisibility = function() {
  return /** @type {!proto.statistico.VisibilityEnum} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {!proto.statistico.VisibilityEnum} value */
proto.statistico.Strategy.prototype.setVisibility = function(value) {
  jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional StrategyStatusEnum status = 12;
 * @return {!proto.statistico.StrategyStatusEnum}
 */
proto.statistico.Strategy.prototype.getStatus = function() {
  return /** @type {!proto.statistico.StrategyStatusEnum} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {!proto.statistico.StrategyStatusEnum} value */
proto.statistico.Strategy.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional StakingPlan staking_plan = 13;
 * @return {?proto.statistico.StakingPlan}
 */
proto.statistico.Strategy.prototype.getStakingPlan = function() {
  return /** @type{?proto.statistico.StakingPlan} */ (
    jspb.Message.getWrapperField(this, proto.statistico.StakingPlan, 13));
};


/** @param {?proto.statistico.StakingPlan|undefined} value */
proto.statistico.Strategy.prototype.setStakingPlan = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


proto.statistico.Strategy.prototype.clearStakingPlan = function() {
  this.setStakingPlan(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.Strategy.prototype.hasStakingPlan = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * repeated ResultFilter result_filters = 14;
 * @return {!Array<!proto.statistico.ResultFilter>}
 */
proto.statistico.Strategy.prototype.getResultFiltersList = function() {
  return /** @type{!Array<!proto.statistico.ResultFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.ResultFilter, 14));
};


/** @param {!Array<!proto.statistico.ResultFilter>} value */
proto.statistico.Strategy.prototype.setResultFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.statistico.ResultFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.ResultFilter}
 */
proto.statistico.Strategy.prototype.addResultFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.statistico.ResultFilter, opt_index);
};


proto.statistico.Strategy.prototype.clearResultFiltersList = function() {
  this.setResultFiltersList([]);
};


/**
 * repeated StatFilter stat_filters = 15;
 * @return {!Array<!proto.statistico.StatFilter>}
 */
proto.statistico.Strategy.prototype.getStatFiltersList = function() {
  return /** @type{!Array<!proto.statistico.StatFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.StatFilter, 15));
};


/** @param {!Array<!proto.statistico.StatFilter>} value */
proto.statistico.Strategy.prototype.setStatFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.statistico.StatFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.StatFilter}
 */
proto.statistico.Strategy.prototype.addStatFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.statistico.StatFilter, opt_index);
};


proto.statistico.Strategy.prototype.clearStatFiltersList = function() {
  this.setStatFiltersList([]);
};


/**
 * optional google.protobuf.Timestamp created_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Strategy.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.Strategy.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 16, value);
};


proto.statistico.Strategy.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.Strategy.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 17;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Strategy.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 17));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.Strategy.prototype.setUpdatedAt = function(value) {
  jspb.Message.setWrapperField(this, 17, value);
};


proto.statistico.Strategy.prototype.clearUpdatedAt = function() {
  this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.Strategy.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 17) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.StrategyTrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.statistico.StrategyTrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.StrategyTrade.displayName = 'proto.statistico.StrategyTrade';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.StrategyTrade.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.StrategyTrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.StrategyTrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTrade.toObject = function(includeInstance, msg) {
  var f, obj = {
    marketName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runnerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    runnerPrice: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    side: jspb.Message.getFieldWithDefault(msg, 4, 0),
    eventId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    competitionId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    seasonId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    eventDate: (f = msg.getEventDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    result: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.StrategyTrade}
 */
proto.statistico.StrategyTrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.StrategyTrade;
  return proto.statistico.StrategyTrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.StrategyTrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.StrategyTrade}
 */
proto.statistico.StrategyTrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunnerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRunnerPrice(value);
      break;
    case 4:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEventId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCompetitionId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSeasonId(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEventDate(value);
      break;
    case 9:
      var value = /** @type {!proto.statistico.TradeResultEnum} */ (reader.readEnum());
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.StrategyTrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.StrategyTrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.StrategyTrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarketName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunnerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRunnerPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getEventId();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getCompetitionId();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getSeasonId();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getEventDate();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional string market_name = 1;
 * @return {string}
 */
proto.statistico.StrategyTrade.prototype.getMarketName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.statistico.StrategyTrade.prototype.setMarketName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string runner_name = 2;
 * @return {string}
 */
proto.statistico.StrategyTrade.prototype.getRunnerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.statistico.StrategyTrade.prototype.setRunnerName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float runner_price = 3;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getRunnerPrice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setRunnerPrice = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional SideEnum side = 4;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.StrategyTrade.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.statistico.SideEnum} value */
proto.statistico.StrategyTrade.prototype.setSide = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional uint64 event_id = 5;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setEventId = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 competition_id = 6;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getCompetitionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setCompetitionId = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 season_id = 7;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getSeasonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.statistico.StrategyTrade.prototype.setSeasonId = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional google.protobuf.Timestamp event_date = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.StrategyTrade.prototype.getEventDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.statistico.StrategyTrade.prototype.setEventDate = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.statistico.StrategyTrade.prototype.clearEventDate = function() {
  this.setEventDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.statistico.StrategyTrade.prototype.hasEventDate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional TradeResultEnum result = 9;
 * @return {!proto.statistico.TradeResultEnum}
 */
proto.statistico.StrategyTrade.prototype.getResult = function() {
  return /** @type {!proto.statistico.TradeResultEnum} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.statistico.TradeResultEnum} value */
proto.statistico.StrategyTrade.prototype.setResult = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.StakingPlan = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.statistico.StakingPlan, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.statistico.StakingPlan.displayName = 'proto.statistico.StakingPlan';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.StakingPlan.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.StakingPlan.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.StakingPlan} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StakingPlan.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: +jspb.Message.getFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.StakingPlan}
 */
proto.statistico.StakingPlan.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.StakingPlan;
  return proto.statistico.StakingPlan.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.StakingPlan} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.StakingPlan}
 */
proto.statistico.StakingPlan.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.statistico.StakingPlanEnum} */ (reader.readEnum());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.StakingPlan.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.StakingPlan.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.StakingPlan} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StakingPlan.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional StakingPlanEnum name = 1;
 * @return {!proto.statistico.StakingPlanEnum}
 */
proto.statistico.StakingPlan.prototype.getName = function() {
  return /** @type {!proto.statistico.StakingPlanEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.statistico.StakingPlanEnum} value */
proto.statistico.StakingPlan.prototype.setName = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional float value = 2;
 * @return {number}
 */
proto.statistico.StakingPlan.prototype.getValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.statistico.StakingPlan.prototype.setValue = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


goog.object.extend(exports, proto.statistico);
