// source: strategy.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var enum_pb = require('./enum_pb.js');
goog.object.extend(proto, enum_pb);
var filter_pb = require('./filter_pb.js');
goog.object.extend(proto, filter_pb);
var requests_pb = require('./requests_pb.js');
goog.object.extend(proto, requests_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.statistico.Strategy', null, global);
goog.exportSymbol('proto.statistico.StrategyTrade', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.Strategy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.statistico.Strategy.repeatedFields_, null);
};
goog.inherits(proto.statistico.Strategy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.statistico.Strategy.displayName = 'proto.statistico.Strategy';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.statistico.StrategyTrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.statistico.StrategyTrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.statistico.StrategyTrade.displayName = 'proto.statistico.StrategyTrade';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.statistico.Strategy.repeatedFields_ = [9,13,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.Strategy.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.Strategy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.Strategy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.Strategy.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    market: jspb.Message.getFieldWithDefault(msg, 5, ""),
    runner: jspb.Message.getFieldWithDefault(msg, 6, ""),
    minOdds: (f = msg.getMinOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    maxOdds: (f = msg.getMaxOdds()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    competitionIdsList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    side: jspb.Message.getFieldWithDefault(msg, 10, 0),
    visibility: jspb.Message.getFieldWithDefault(msg, 11, 0),
    status: jspb.Message.getFieldWithDefault(msg, 12, 0),
    resultFiltersList: jspb.Message.toObjectList(msg.getResultFiltersList(),
    filter_pb.ResultFilter.toObject, includeInstance),
    statFiltersList: jspb.Message.toObjectList(msg.getStatFiltersList(),
    filter_pb.StatFilter.toObject, includeInstance),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.Strategy}
 */
proto.statistico.Strategy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.Strategy;
  return proto.statistico.Strategy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.Strategy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.Strategy}
 */
proto.statistico.Strategy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunner(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMinOdds(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setMaxOdds(value);
      break;
    case 9:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addCompetitionIds(values[i]);
      }
      break;
    case 10:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 11:
      var value = /** @type {!proto.statistico.VisibilityEnum} */ (reader.readEnum());
      msg.setVisibility(value);
      break;
    case 12:
      var value = /** @type {!proto.statistico.StrategyStatusEnum} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 13:
      var value = new filter_pb.ResultFilter;
      reader.readMessage(value,filter_pb.ResultFilter.deserializeBinaryFromReader);
      msg.addResultFilters(value);
      break;
    case 14:
      var value = new filter_pb.StatFilter;
      reader.readMessage(value,filter_pb.StatFilter.deserializeBinaryFromReader);
      msg.addStatFilters(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.Strategy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.Strategy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.Strategy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.Strategy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRunner();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMinOdds();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getMaxOdds();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getCompetitionIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      9,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getVisibility();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getResultFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      filter_pb.ResultFilter.serializeBinaryToWriter
    );
  }
  f = message.getStatFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      filter_pb.StatFilter.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string user_id = 4;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string market = 5;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setMarket = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string runner = 6;
 * @return {string}
 */
proto.statistico.Strategy.prototype.getRunner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setRunner = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional google.protobuf.FloatValue min_odds = 7;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.Strategy.prototype.getMinOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 7));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.statistico.Strategy} returns this
*/
proto.statistico.Strategy.prototype.setMinOdds = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearMinOdds = function() {
  return this.setMinOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Strategy.prototype.hasMinOdds = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.FloatValue max_odds = 8;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.statistico.Strategy.prototype.getMaxOdds = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 8));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.statistico.Strategy} returns this
*/
proto.statistico.Strategy.prototype.setMaxOdds = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearMaxOdds = function() {
  return this.setMaxOdds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Strategy.prototype.hasMaxOdds = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated uint64 competition_ids = 9;
 * @return {!Array<number>}
 */
proto.statistico.Strategy.prototype.getCompetitionIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setCompetitionIdsList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.addCompetitionIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearCompetitionIdsList = function() {
  return this.setCompetitionIdsList([]);
};


/**
 * optional SideEnum side = 10;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.Strategy.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.statistico.SideEnum} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setSide = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * optional VisibilityEnum visibility = 11;
 * @return {!proto.statistico.VisibilityEnum}
 */
proto.statistico.Strategy.prototype.getVisibility = function() {
  return /** @type {!proto.statistico.VisibilityEnum} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {!proto.statistico.VisibilityEnum} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setVisibility = function(value) {
  return jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional StrategyStatusEnum status = 12;
 * @return {!proto.statistico.StrategyStatusEnum}
 */
proto.statistico.Strategy.prototype.getStatus = function() {
  return /** @type {!proto.statistico.StrategyStatusEnum} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.statistico.StrategyStatusEnum} value
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * repeated ResultFilter result_filters = 13;
 * @return {!Array<!proto.statistico.ResultFilter>}
 */
proto.statistico.Strategy.prototype.getResultFiltersList = function() {
  return /** @type{!Array<!proto.statistico.ResultFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.ResultFilter, 13));
};


/**
 * @param {!Array<!proto.statistico.ResultFilter>} value
 * @return {!proto.statistico.Strategy} returns this
*/
proto.statistico.Strategy.prototype.setResultFiltersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.statistico.ResultFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.ResultFilter}
 */
proto.statistico.Strategy.prototype.addResultFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.statistico.ResultFilter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearResultFiltersList = function() {
  return this.setResultFiltersList([]);
};


/**
 * repeated StatFilter stat_filters = 14;
 * @return {!Array<!proto.statistico.StatFilter>}
 */
proto.statistico.Strategy.prototype.getStatFiltersList = function() {
  return /** @type{!Array<!proto.statistico.StatFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, filter_pb.StatFilter, 14));
};


/**
 * @param {!Array<!proto.statistico.StatFilter>} value
 * @return {!proto.statistico.Strategy} returns this
*/
proto.statistico.Strategy.prototype.setStatFiltersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.statistico.StatFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.statistico.StatFilter}
 */
proto.statistico.Strategy.prototype.addStatFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.statistico.StatFilter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearStatFiltersList = function() {
  return this.setStatFiltersList([]);
};


/**
 * optional google.protobuf.Timestamp created_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Strategy.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.statistico.Strategy} returns this
*/
proto.statistico.Strategy.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Strategy.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.Strategy.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.statistico.Strategy} returns this
*/
proto.statistico.Strategy.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.Strategy} returns this
 */
proto.statistico.Strategy.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.Strategy.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.statistico.StrategyTrade.prototype.toObject = function(opt_includeInstance) {
  return proto.statistico.StrategyTrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.statistico.StrategyTrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTrade.toObject = function(includeInstance, msg) {
  var f, obj = {
    marketName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runnerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    runnerPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    side: jspb.Message.getFieldWithDefault(msg, 4, 0),
    eventId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    competitionId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    seasonId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    eventDate: (f = msg.getEventDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    result: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.statistico.StrategyTrade}
 */
proto.statistico.StrategyTrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.statistico.StrategyTrade;
  return proto.statistico.StrategyTrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.statistico.StrategyTrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.statistico.StrategyTrade}
 */
proto.statistico.StrategyTrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunnerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRunnerPrice(value);
      break;
    case 4:
      var value = /** @type {!proto.statistico.SideEnum} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEventId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCompetitionId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSeasonId(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEventDate(value);
      break;
    case 9:
      var value = /** @type {!proto.statistico.TradeResultEnum} */ (reader.readEnum());
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.statistico.StrategyTrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.statistico.StrategyTrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.statistico.StrategyTrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.statistico.StrategyTrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarketName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunnerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRunnerPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getEventId();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getCompetitionId();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getSeasonId();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getEventDate();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional string market_name = 1;
 * @return {string}
 */
proto.statistico.StrategyTrade.prototype.getMarketName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setMarketName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string runner_name = 2;
 * @return {string}
 */
proto.statistico.StrategyTrade.prototype.getRunnerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setRunnerName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float runner_price = 3;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getRunnerPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setRunnerPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional SideEnum side = 4;
 * @return {!proto.statistico.SideEnum}
 */
proto.statistico.StrategyTrade.prototype.getSide = function() {
  return /** @type {!proto.statistico.SideEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.statistico.SideEnum} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setSide = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional uint64 event_id = 5;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setEventId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 competition_id = 6;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getCompetitionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setCompetitionId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 season_id = 7;
 * @return {number}
 */
proto.statistico.StrategyTrade.prototype.getSeasonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setSeasonId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional google.protobuf.Timestamp event_date = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.statistico.StrategyTrade.prototype.getEventDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.statistico.StrategyTrade} returns this
*/
proto.statistico.StrategyTrade.prototype.setEventDate = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.clearEventDate = function() {
  return this.setEventDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.statistico.StrategyTrade.prototype.hasEventDate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional TradeResultEnum result = 9;
 * @return {!proto.statistico.TradeResultEnum}
 */
proto.statistico.StrategyTrade.prototype.getResult = function() {
  return /** @type {!proto.statistico.TradeResultEnum} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.statistico.TradeResultEnum} value
 * @return {!proto.statistico.StrategyTrade} returns this
 */
proto.statistico.StrategyTrade.prototype.setResult = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


goog.object.extend(exports, proto.statistico);
